### ISSUE TITLE
Hacking Journalism

### ISSUE THREAD

**Issue by amandasullivan** [japacible/Hackathon-Calendar#45]
The Hacking Journalism website links to a Hackathon that occurred on January 17-18 2015, in NYC.

2014 Hacking Journalism was held on June 8th, but I can't find any information about a 2nd 2015 Hackathon in June. I'm assuming the Calendar just used last years dates and wasn't updated in time for the new date.

**Comment by japacible** [comment]
Thanks for catching this! The Calendar isn't intended to just copy over hackathons from one year to the next, but only add them when there's a new date confirmed.

I added Hacking Journalism in December, so I must have misread the year on the old site. :(
