### ISSUE TITLE
Two more hackathons to add!

### ISSUE THREAD

**Issue by gauss1181** [japacible/Hackathon-Calendar#49]
HackOTR - March 6-7, 2015 - Cincinnati, OH
http://www.hackotr.com

HackPrinceton - April 11-12, 2015 - Princeton, NJ
http://www.hackprinceton.com

**Comment by japacible** [comment]
Added HackOTR in past hackathons for the record, and HackPrinceton is already on the schedule.  18e000b30da3cbd1c16837a23d828e4b846df215
