### ISSUE TITLE
AC Apps Challenge 2015 Hackathon

### ISSUE THREAD

**Issue by manxyblue** [japacible/Hackathon-Calendar#52]
When: April 25th 
Where: James Logan High School in Union City 
Time: 8:30 AM - 7:00 PM 
Register @ http://code.acgov.org 
Prizes: 1st Prize $3,000 | 2nd Prize $1500 | 3rd Prize $500

Create a unique App that benefits the residents, visitors, and/or business owners of Alameda County using one of Alameda County's datasets (http://data.acgov.org). 
Visit http://code.acgov.org for more event information and registration. 
A fun event challenging your technical skills and creativity. 
Please Forward and Share.

**Comment by japacible** [comment]
Added to past hackathons file.
