### ISSUE TITLE
Add Seattle hackathons

### ISSUE THREAD

**Issue by gauss1181** [japacible/Hackathon-Calendar#56]
Saturday, May 30 to Sunday, May 31: Microsoft Big Data Hackathon
Saturday, June 27 to Sunday, June 28: AngelHack Seattle

**Comment by japacible** [comment]
URLs, please?

**Comment by gauss1181** [comment]
AngelHack Seattle: http://angelhack.com/hackathon/seattle-2015/
Microsoft Big Data Hackathon: https://msevents.microsoft.com/CUI/EventDetail.aspx?EventID=1032622104&Culture=en-US&community=0&WT.mc_id=Blog_SQL_Announce_DI

**Comment by japacible** [comment]
Added. Thanks!
