### ISSUE TITLE
The Global Mobile Innovators Tournament - Enabled  by IBM & 4YFN

### ISSUE THREAD

**Issue by EcoDEurope** [japacible/Hackathon-Calendar#72]
NEW ONLINE HACKATHON LAUNCHED. Can this be added to the 'Upcoming Hackathons' list please?

"Just launched, the Global Mobile Innovators Tournament uses IBM’s Bluemix as a platform to help you create game changing mobile apps, get your start-ups off the ground and be noticed by potential investors! Register your interest today to begin leveraging free resources to learn more about IBM Bluemix and for the chance to win a trip to Barcelona to compete in the Finale in February 2016!" 

Platform link: www.glovators.io

**Comment by japacible** [comment]
I'd consider this a long term project competition rather than a hackathon.
