### ISSUE TITLE
WearHacks World Tour

### ISSUE THREAD

**Issue by makrandgupta** [japacible/Hackathon-Calendar#85]
WearHacks Montreal: Oct 2 - 4
WearHacks New York: Oct 23-25
WearHacks LA: Nov 6-8
WearHacks Waterloo: Nov 20-22

**Comment by djr-** [comment]
Both the WearHacks Waterloo and the WearHacks Vancouver links are currently broken (see http://www.wearhacks.com/), but I have added the others in the following pull request:

https://github.com/japacible/Hackathon-Calendar/pull/87

**Comment by japacible** [comment]
Merged #87.

Added [WearHacks Waterloo](http://waterloo.wearhacks.com/). Vancouver looks to be a private event. If it opens up to the public in the future, feel free to send a PR.

**Comment by makrandgupta** [comment]
Thanks! I will keep you posted with updates. This is something you might want to add http://hacktoberfest.splashthat.com/ should I issue a new pull request for it?
